"""Stock universes.

`curated` is a hand-picked list of liquid NSE large and mid caps (roughly the
Nifty 200). It keeps a daily refresh to a few minutes under Upstox's request
limits. `nse_all` uses every NSE cash-equity in the instrument master and relies
on the liquidity filter inside the strategy; the first refresh takes ~30 min.
"""
from __future__ import annotations

import pandas as pd

CURATED_SYMBOLS: list[str] = """
RELIANCE TCS HDFCBANK ICICIBANK INFY BHARTIARTL ITC SBIN LICI HINDUNILVR LT BAJFINANCE HCLTECH
MARUTI SUNPHARMA KOTAKBANK AXISBANK NTPC ONGC TITAN ADANIENT ADANIPORTS ULTRACEMCO ASIANPAINT
POWERGRID WIPRO M&M BAJAJFINSV COALINDIA TATAMOTORS NESTLEIND TATASTEEL HAL JSWSTEEL BAJAJ-AUTO
DLF IOC GRASIM ADANIGREEN ADANIPOWER SIEMENS HINDALCO TECHM VBL BEL LTIM PIDILITIND BPCL
INDUSINDBK SBILIFE GODREJCP EICHERMOT HDFCLIFE DIVISLAB BRITANNIA CIPLA TRENT DRREDDY BANKBARODA
PNB ABB TATAPOWER AMBUJACEM ZOMATO IRFC HAVELLS APOLLOHOSP JIOFIN CHOLAFIN TVSMOTOR SHRIRAMFIN
INDIGO BOSCHLTD GAIL DABUR VEDL HEROMOTOCO CANBK UNIONBANK IOB BAJAJHLDNG TORNTPHARM MOTHERSON
ICICIPRULI ICICIGI SHREECEM LODHA CGPOWER POLYCAB PFC RECLTD UNITDSPR MANKIND BERGEPAINT MARICO
COLPAL ZYDUSLIFE JINDALSTEL HINDZINC SRF NHPC CUMMINSIND LUPIN TATACONSUM MAXHEALTH ATGL BHEL
IDBI INDHOTEL PERSISTENT OBEROIRLTY AUROPHARMA NAUKRI SBICARD MUTHOOTFIN SOLARINDS SAIL NMDC
TIINDIA ASHOKLEY OIL SUZLON YESBANK IDFCFIRSTB ALKEM PATANJALI ABCAPITAL BHARATFORG BALKRISIND
GMRINFRA PIIND ASTRAL MPHASIS COFORGE OFSS TATACOMM DIXON HDFCAMC KPITTECH LTF SUPREMEIND
PRESTIGE MAZDOCK COCHINSHIP RVNL PHOENIXLTD FEDERALBNK AUBANK BANDHANBNK APLAPOLLO GODREJPROP
PETRONET HINDPETRO IRCTC POLICYBZR PAYTM NYKAA DELHIVERY MFSL LICHSGFIN VOLTAS TATAELXSI
UPL CONCOR ESCORTS EXIDEIND PAGEIND JUBLFOOD MRF APOLLOTYRE CROMPTON KALYANKJIL SONACOMS
DEEPAKNTR NAVINFLUOR LAURUSLABS GLENMARK BIOCON SYNGENE IPCALAB FORTIS ABBOTINDIA GLAXO
SUNTV ZEEL PVRINOX INDUSTOWER BSE MCX CDSL ANGELONE 360ONE KEI BLUESTARCO THERMAX HONAUT
ACC DALBHARAT JKCEMENT RAMCOCEM NATIONALUM HINDCOPPER JSWENERGY TORNTPOWER CESC SJVN
""".split()


def curated_symbols() -> list[str]:
    seen: set[str] = set()
    out = []
    for s in CURATED_SYMBOLS:
        if s not in seen:
            seen.add(s)
            out.append(s)
    return out


def select_universe(instruments: pd.DataFrame, mode: str) -> tuple[pd.DataFrame, list[str]]:
    """Returns (instrument rows to scan, curated symbols that were not found)."""
    if mode == "nse_all" or instruments.empty:
        return instruments.copy(), []
    wanted = curated_symbols()
    found = instruments[instruments["symbol"].isin(wanted)].copy()
    missing = sorted(set(wanted) - set(found["symbol"]))
    return found, missing
